AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Description: "Project name"
    Type: "String"
  Environment:
    Description: "Server environment"
    Type: "String"
    AllowedValues:
      - "dev"
  LocalDevUserARN:
    Type: "String"

Resources:
  DevRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-role"
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Ref "LocalDevUserARN"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"

Outputs:
  ConsumerRoleName:
    Value: !Ref "DevRole"
  ConsumerRoleARN:
    Value: !GetAtt "DevRole.Arn"
