AWSTemplateFormatVersion: "2010-09-09"
Description: "Database setup in RDS"
Parameters:
  ProjectName:
    Description: "Project name"
    Type: "String"
  Environment:
    Description: "Server environment"
    Type: "String"
    AllowedValues:
      - "test"
      - "prod"
  DatabaseName:
    Description: "Database name"
    Type: "String"
    Default: "ebdb"
  DatabaseEngineVersion:
    Description: "Database Engine version"
    Type: "String"
  DatabaseInstanceClass:
    Description: "Database instance class"
    Type: "String"
    Default: "db.t3.micro"
  DatabaseUsername:
    Description: "Username for master user in RDS database"
    Type: "String"
    Default: "postgres"
  DatabasePassword:
    Description: "Password for master user in RDS database"
    Type: "String"
    NoEcho: true
  DatabasePort:
    Description: "Port for RDS"
    Type: "String"
    Default: "5432"
  RDSMonitoringRoleARN:
    Description: "ARN for RDS monitoring role"
    Type: "String"
  VpcId:
    Type: "String"
  SubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"

Resources:
  DatabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${ProjectName}-${Environment}-rds-sg"
      GroupDescription: "RDS database security group"
      VpcId: !Ref "VpcId"
      Tags:
        - Key: "Name"
          Value: !Sub "${ProjectName}-${Environment}-rds-sg"
        - Key: "project-name"
          Value: !Ref "ProjectName"
        - Key: "environment"
          Value: !Ref "Environment"

  DatabaseSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      SubnetIds: !Ref "SubnetIds"
      DBSubnetGroupName: !Sub "${ProjectName}-${Environment}-subnet-group"
      DBSubnetGroupDescription: !Sub "${ProjectName}-${Environment}-subnet-group"
      Tags:
        - Key: "project-name"
          Value: !Ref "ProjectName"
        - Key: "environment"
          Value: !Ref "Environment"
  Database:
    Type: "AWS::RDS::DBInstance"
    Properties:
      VPCSecurityGroups:
        - !Ref "DatabaseSecurityGroup"
      Engine: "postgres"
      EngineVersion: !Ref "DatabaseEngineVersion"
      DBName: !Ref "DatabaseName"
      Port: !Ref "DatabasePort"
      DBInstanceIdentifier: !Sub "${ProjectName}-${Environment}"
      MasterUsername: !Ref "DatabaseUsername"
      MasterUserPassword: !Ref "DatabasePassword"
      DBInstanceClass: !Ref "DatabaseInstanceClass"
      AllocatedStorage: "20"
      StorageType: "gp2"
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      MultiAZ: false
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "02:00-02:30"
      EnablePerformanceInsights: true
      MonitoringInterval: 60
      MonitoringRoleArn: !Ref "RDSMonitoringRoleARN"
      AutoMinorVersionUpgrade: true
      PreferredMaintenanceWindow: "Sat:05:00-Sat:05:30"
      DeletionProtection: false #TODO Set to true once we finish
      Tags:
        - Key: "project-name"
          Value: !Ref "ProjectName"
        - Key: "environment"
          Value: !Ref "Environment"
Outputs:
  RDSAddress:
    Description: "RDS database address"
    Value: !GetAtt "Database.Endpoint.Address"
  RdsSecurityGroupId:
    Description: "RDS security group"
    Value: !Ref "DatabaseSecurityGroup"
