AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  ProjectName:
    Description: "Project name"
    Type: "String"
  Environment:
    Description: "Server environment"
    Type: "String"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
  ConsumerRoleName:
    Type: "String"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "Private"
      BucketName: !Sub "${ProjectName}-${Environment}-env"
      Tags:
        - Key: "project-name"
          Value: !Ref "ProjectName"
        - Key: "environment"
          Value: !Ref "Environment"
  S3BucketPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub "${ProjectName}-${Environment}-env-s3"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:ListBucket"
              - "s3:DeleteObject"
            Resource: !GetAtt "S3bucket.Arn"
      Roles:
        - !Ref "ConsumerRoleName"

Outputs:
  BucketName:
    Value: !Ref "S3bucket"
