AWSTemplateFormatVersion: "2010-09-09"
Description: "CI IAM User, Groups and Policies"

Parameters:
  ResourceNamePrefix:
    Type: "String"

Resources:
  CIGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${ResourceNamePrefix}-ci"
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
        - "arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk"
  CIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "ci"
      Path: /
      Groups:
        - !Ref "CIGroup"
  CIUserAccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      Status: "Active"
      UserName: !Ref "CIUser"
