AWSTemplateFormatVersion: "2010-09-09"
Description: "CI IAM User, Groups and Policies"

Parameters:
  ResourceNamePrefix:
    Type: "String"

Resources:
  CiGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${ResourceNamePrefix}-ci"
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
        - "arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk"

  CiUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${ResourceNamePrefix}-ci"
      Path: /
      Groups:
        - !Ref "CiGroup"

Outputs:
  CiUserARN:
    Value: !GetAtt "CiUser.Arn"
  CiUserName:
    Value: !Ref "CiUser"
