AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Key Pair creation"

Parameters:
 ProjectName:
    Description: "Project name"
    Type: "String"
 Environment:
    Description: "Server environment"
    Type: "String"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"

# The generated KeyPair is stored in AWS System Manager Parameter Store
# in the path /ec2/keypair/{key_pair_id}.
Resources: 
  EC2KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Sub "${ProjectName}-${Environment}" 

Outputs:
  EC2KeyPairName:
    Value: !Ref "EC2KeyPair"