AWSTemplateFormatVersion: "2010-09-09"
Description: "Database setup in RDS"
Parameters:
  ProjectName:
    Description: "Project name"
    Type: "String"
  Environment:
    Description: "Server environment"
    Type: "String"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
  DatabaseName:
    Description: "Database name"
    Type: "String"
    Default: "ebdb"
  DatabaseEngineVersion:
    Description: "Database Engine version"
    Type: "String"
  DatabaseInstanceClass:
    Description: "Database instance class"
    Type: "String"
    Default: "db.t3.micro"
  RDSMonitoringRoleARN:
    Description: "ARN for RDS monitoring role"
    Type: "String"
  VpcId:
    Type: "String"
  Subnets:
    Type: "List<AWS::EC2::Subnet::Id>"
Resources:
  DatabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "RDS Microservices security group"
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      VpcId: !Ref "VpcId"
  DatabaseSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      SubnetIds: !Ref "Subnets"
      DBSubnetGroupName: !Sub "${ProjectName}-${Environment}"
      DBSubnetGroupDescription: "Subnet group for the DB"
  Database:
    Type: "AWS::RDS::DBInstance"
    Properties:
      VPCSecurityGroups:
        - !Ref "DatabaseSecurityGroup"
      Engine: "postgres"
      EngineVersion: !Ref "DatabaseEngineVersion"
      DBName: !Ref "DatabaseName"
      DBInstanceIdentifier: !Sub "${ProjectName}-${Environment}"
      # MasterUsername: "postgres"
      # MasterUserPassword: "safepassword" # Don't hardcode passwords
      DBInstanceClass: !Ref "DatabaseInstanceClass"
      AllocatedStorage: "20"
      StorageType: "gp2"
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      MultiAZ: false
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "0224:00-0224:30"
      EnablePerformanceInsights: true
      MonitoringInterval: 60
      MonitoringRoleArn: !Ref "RDSMonitoringRoleARN"
Outputs:
  RDSAddress:
    Description: "RDS database address"
    Value: !GetAtt "Database.Endpoint.Address"
  RDSSecurityGroup:
    Description: "RDS security group"
    Value: !Ref "DatabaseSecurityGroup"
