AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Description: "Project name"
    Type: "String"
  LocalDevUserARN:
    Type: "String"

Resources:
  DevRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectName}-dev-eb-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Ref "LocalDevUserARN"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"

Outputs:
  RoleName:
    Value: !Ref "DevRole"