AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM role for the AEB service"

Parameters:
  ResourceNamePrefix:
    Type: "String"

Resources:
  AebServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ResourceNamePrefix}-aws-elasticbeanstalk-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "elasticbeanstalk.amazonaws.com"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: "elasticbeanstalk"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth"
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy"

Outputs:
  EbServiceRoleARN:
    Value: !GetAtt "AebServiceRole.Arn"
