name: CI

on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  cloudformation-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t resources/infrastructure/cloudformation-templates/**/*.yaml --format=pretty
  clojure-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@12.6
        with:
          clj-kondo: 2024.03.13

      - name: Install Babashka
        run: |
          curl --location --output bb.tar.gz "https://github.com/babashka/babashka/releases/download/v1.3.189/babashka-1.3.189-linux-amd64.tar.gz"
          tar xf bb.tar.gz
          chmod +x ./bb

      - name: Lint
        run: clj-kondo --lint src

      - name: Build Uberjar
        run: |
          ./bb uberjar hop-cli.jar --main hop-cli.main

      - name: Release Uberjar
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'refs/tags/')
        with:
          files: hop-cli.jar
