name: Lint CloudFormation Templates

on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint resources/**/*.yaml --format=pretty
  babashka-ssm-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.10.05'

      - name: Install Babashka
        run: |
          curl -L --output bb.tar.gz https://github.com/babashka/babashka/releases/download/v0.10.163/babashka-0.10.163-linux-amd64.tar.gz
          tar xf bb.tar.gz
          chmod +x ./bb

      - name: Lint
        run: clj-kondo --lint bb-scripts/src

      - name: Build Uberjar
        run: |
          cd bb-scripts
          ../bb uberjar ssm-parameter-store-sync.jar -m hop.aws.cli

      - name: Release Uberjar
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'refs/tags/')
        with:
          files: bb-scripts/ssm-parameter-store-sync.jar
